### ISSUE TITLE
Roadmap v2.0

### ISSUE THREAD

**Issue by stoffern** [stoffern/extensive-react-server#3]
## Features

- Gives the posibility to add multiple SSR projects onto one server. Example: client page + authed admin page
- Alot easier to configure the server.
- Easier to use functions to add what is needed

## TODO
- [x] Move execution out of universal-app-cli into JSON.
- [x] Start server form index.js creating a new object of the server.
- [x] Pass settings to the server object, logging, security etc.
- [x] Make a function to add Webpack SSR configs to render with prefix inside server object
- [x] Add routes and route folders inside server object

**Comment by stoffern** [comment]
done v2.0.0
